# OBJECT ORIENTED PROGRAMMING
# COMMON TOPIC IN ALMOST ALL POPULAR PROGRAMING LANGUAGES(PYTHON,
# WITH COMMON IDEA BUT WITH DIFFERENT SYNTAX
# OOP IS JUST A STYLE/WAY TO WRITE A CODE
# VERY HELPFUL IN CREATING REAL WORLD PROGRAMS
# JAVA)
# # WE WILL
# class
# SEE OTHER ADVANTAGES WHEN WE WILL START LEARNING OOP

# wject(instance), method

# list class   
# list object
# method


